# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib savvyex, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_savvyex__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_savvyex__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Multiply Input By Another Input
#'
#' @param x An integer vector.
#' @param y An integer to multiply.
#' @returns An integer vector with values multiplied by `y`.
#' @export
`int_times_int` <- function(`x`, `y`) {
  .Call(savvy_int_times_int__impl, `x`, `y`)
}

#' Convert Input To Upper-Case
#'
#' @param x A character vector.
#' @returns A character vector with upper case version of the input.
#' @export
`to_upper` <- function(`x`) {
  .Call(savvy_to_upper__impl, `x`)
}

### wrapper functions for Patient

`Patient_name` <- function(self) {
  function() {
    .Call(savvy_Patient_name__impl, `self`)
  }
}

`Patient_set_name` <- function(self) {
  function(`first_name`, `middle_name`, `last_name`) {
    invisible(.Call(savvy_Patient_set_name__impl, `self`, `first_name`, `middle_name`, `last_name`))
  }
}

`.savvy_wrap_Patient` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`name` <- `Patient_name`(ptr)
  e$`set_name` <- `Patient_set_name`(ptr)

  class(e) <- c("savvyex::Patient", "Patient", "savvy_savvyex__sealed")
  e
}



`Patient` <- new.env(parent = emptyenv())

### associated functions for Patient

`Patient`$`associated_function` <- function() {
  .Call(savvy_Patient_associated_function__impl)
}

`Patient`$`new` <- function() {
  .savvy_wrap_Patient(.Call(savvy_Patient_new__impl))
}


class(`Patient`) <- c("savvyex::Patient__bundle", "savvy_savvyex__sealed")

#' @export
`print.savvyex::Patient__bundle` <- function(x, ...) {
  cat('savvyex::Patient\n')
}

